import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();

function read(relativePath) {
  return readFileSync(join(root, relativePath), 'utf8');
}

test('ships the seed festival data for the homepage vertical slice', () => {
  const dataPath = 'src/data/seed_festivals_10.json';
  assert.equal(existsSync(join(root, dataPath)), true, 'seed data should be available in src/data');

  const data = JSON.parse(read(dataPath));
  assert.equal(data.festivals.length, 10);
  assert.equal(new Set(data.festivals.map((record) => record.record_id)).size, 10);
  assert.equal(data.festivals.every((record) => record.official_url && record.source_confidence === 'high'), true);
  assert.equal(data.festivals.every((record) => record.latitude === null && record.longitude === null), true);
});

test('homepage contains the required RetroAltFest MVP sections and CTAs', () => {
  const homepageSource = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FeaturedFestivals.tsx',
    'src/components/home/SceneChips.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/home/MapPreview.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
  ]
    .filter((sourcePath) => existsSync(join(root, sourcePath)))
    .map(read)
    .join('\n');

  const requiredCopy = [
    'Discover dark alternative festivals worth traveling for.',
    'Browse festivals',
    'Suggest a festival',
    'Map preview',
    'Featured festivals',
    'Browse by scene',
    'Built for fewer dead ends.',
    'Official sources',
    'Clear status labels',
    'Manual curation',
  ];

  for (const copy of requiredCopy) {
    assert.match(homepageSource, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});

test('homepage removes generated template branding and deploy links', () => {
  const homepageSource = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/site/Footer.tsx',
  ]
    .filter((sourcePath) => existsSync(join(root, sourcePath)))
    .map(read)
    .join('\n');

  assert.doesNotMatch(homepageSource, /Next\.js logo|Deploy Now|Templates|Documentation|vercel\.com\/new/);
});

test('global styles define the Nocturnal Atlas design tokens and accessible motion behavior', () => {
  const css = read('src/app/globals.css');
  const requiredTokens = ['--raf-black', '--raf-night', '--raf-violet', '--raf-cyan', '--raf-verified', '--raf-warning'];

  for (const token of requiredTokens) {
    assert.match(css, new RegExp(token));
  }

  assert.match(css, /prefers-reduced-motion/);
});

test('metadata is production-ready for RetroAltFest sharing', () => {
  const layout = read('src/app/layout.tsx');
  assert.match(layout, /RetroAltFest/);
  assert.match(layout, /curated/i);
  assert.match(layout, /dark alternative/i);
  assert.doesNotMatch(layout, /Create Next App|Generated by create next app/);
});

test('homepage MVP uses clean component structure and footer', () => {
  const componentPaths = [
    'src/components/site/Header.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FeaturedFestivals.tsx',
    'src/components/home/SceneChips.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/home/MapPreview.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
    'src/components/site/Footer.tsx',
  ];

  for (const componentPath of componentPaths) {
    assert.equal(existsSync(join(root, componentPath)), true, `${componentPath} should exist`);
  }

  const page = read('src/app/page.tsx');
  assert.match(page, /<Hero/);
  assert.match(page, /<FeaturedFestivals/);
  assert.match(page, /<Footer/);
  assert.doesNotMatch(page, /function FestivalCard/);
});

test('README documents setup, structure, run, and deployment guidance', () => {
  const readme = read('README.md');
  const requiredHeadings = [
    'Project initialization commands',
    'Folder/file structure',
    'Run instructions',
    'Deployment recommendations',
  ];

  for (const heading of requiredHeadings) {
    assert.match(readme, new RegExp(heading, 'i'));
  }
});

test('visual refinement pass deepens atmosphere without heavy dependencies', () => {
  const css = read('src/app/globals.css');
  const source = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FestivalCard.tsx',
    'src/components/home/MapPreview.tsx',
  ].map(read).join('\n');

  for (const token of ['ambient-haze', 'grain-field', 'atlas-node', 'connection-arc', 'verification-glyph']) {
    assert.match(`${css}\n${source}`, new RegExp(token));
  }

  for (const animation of ['raf-drift', 'raf-pulse', 'raf-grain']) {
    assert.match(css, new RegExp(animation));
  }

  assert.doesNotMatch(`${css}\n${source}`, /framer-motion|lottie|canvas|three/i);
});

test('visual refinement plan separates MVP-safe upgrades from future enhancements', () => {
  const planPath = 'VISUAL_REFINEMENT_PLAN.md';
  assert.equal(existsSync(join(root, planPath)), true, 'visual refinement plan should exist');
  const plan = read(planPath);

  for (const section of ['UI refinement recommendations', 'Implementation plan', 'MVP-safe upgrades', 'Future enhancements', 'Performance considerations']) {
    assert.match(plan, new RegExp(section, 'i'));
  }
});

test('map preview avoids ambiguous truncated country labels', () => {
  const helpers = read('src/lib/festivals.ts');
  const mapPreview = read('src/components/home/MapPreview.tsx');

  assert.match(helpers, /mapPreviewLabel/);
  assert.match(mapPreview, /mapPreviewLabel\(festival\)/);
  assert.doesNotMatch(mapPreview, /country\.split\(" "\)\[0\]/);
});

test('festival data is expandable for atlas detail pages', () => {
  const data = JSON.parse(read('src/data/seed_festivals_10.json'));
  assert.equal(data.festivals.length, 10);

  for (const festival of data.festivals) {
    assert.match(festival.slug, /^[a-z0-9]+(?:-[a-z0-9]+)*$/);
    assert.equal(typeof festival.atlas_summary, 'string');
    assert.ok(festival.atlas_summary.length > 80);
    assert.equal(typeof festival.why_it_matters, 'string');
    assert.ok(festival.why_it_matters.length > 120);
    assert.ok(Array.isArray(festival.source_links), `${festival.festival_name} should expose labeled source links`);
    assert.ok(festival.source_links.length >= 1);
    assert.ok(festival.source_links.every((link) => link.label && link.url && /^https?:\/\//.test(link.url)));
    assert.ok(Array.isArray(festival.similar_festival_ids), `${festival.festival_name} should list similar festival ids`);
    assert.ok(festival.similar_festival_ids.length >= 2);
  }
});

test('festival detail route is static-first and SEO-ready', () => {
  const detailPath = 'src/app/festivals/[slug]/page.tsx';
  assert.equal(existsSync(join(root, detailPath)), true, 'dynamic festival detail route should exist');

  const detailPage = read(detailPath);
  const helpers = read('src/lib/festivals.ts');

  assert.match(detailPage, /generateStaticParams/);
  assert.match(detailPage, /generateMetadata/);
  assert.match(detailPage, /params: Promise<\{ slug: string \}>/);
  assert.match(detailPage, /notFound\(\)/);
  assert.match(detailPage, /Why this festival matters/);
  assert.match(detailPage, /Official sources/);
  assert.match(detailPage, /Verification notes/);
  assert.match(detailPage, /Similar festivals/);
  assert.match(detailPage, /grid-cols-\[|sm:grid-cols|lg:grid-cols/);
  assert.doesNotMatch(detailPage, /use client|fetch\(|prisma|supabase|mongodb|auth/i);

  assert.match(helpers, /festivalSlug/);
  assert.match(helpers, /getFestivalBySlug/);
  assert.match(helpers, /getSimilarFestivals/);
});

test('homepage cards link into the curated festival atlas', () => {
  const card = read('src/components/home/FestivalCard.tsx');
  assert.match(card, /next\/link/);
  assert.match(card, /href=\{`\/festivals\/\$\{festivalSlug\(festival\)\}`\}/);
  assert.match(card, /View atlas entry/);
});

test('festival directory route lists the atlas with lightweight filters and search', () => {
  const directoryPath = 'src/app/festivals/page.tsx';
  const browserPath = 'src/components/festivals/FestivalDirectoryBrowser.tsx';

  assert.equal(existsSync(join(root, directoryPath)), true, 'static /festivals directory page should exist');
  assert.equal(existsSync(join(root, browserPath)), true, 'directory browser component should exist');

  const directoryPage = read(directoryPath);
  const browser = read(browserPath);

  assert.match(directoryPage, /metadata: Metadata/);
  assert.match(directoryPage, /FestivalDirectoryBrowser/);
  assert.match(directoryPage, /featuredFestivals/);
  assert.match(directoryPage, /Curated festival atlas/);
  assert.doesNotMatch(directoryPage, /fetch\(|prisma|supabase|mongodb|auth|cms/i);

  for (const copy of ['Search by festival or location', 'All scenes', 'All regions', 'All statuses', 'No festivals match']) {
    assert.match(browser, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.match(browser, /use client/);
  assert.match(browser, /useMemo/);
  assert.match(browser, /useState/);
  assert.match(browser, /festivalSlug\(festival\)/);
  assert.match(browser, /\/festivals\/\$\{festivalSlug\(festival\)\}/);
  assert.match(browser, /filteredFestivals\.map/);
  assert.match(browser, /grid gap-4|sm:grid-cols|lg:grid-cols/);
  assert.doesNotMatch(browser, /framer-motion|lottie|three|canvas|axios/i);
});

test('public launch polish adds accessible states and clearer trust microcopy', () => {
  const css = read('src/app/globals.css');
  const source = [
    'src/components/site/Header.tsx',
    'src/components/site/Footer.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FestivalCard.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/festivals/FestivalDirectoryBrowser.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
  ].map(read).join('\n');

  for (const token of ['.raf-button-primary', '.raf-button-secondary', '.raf-chip', '.raf-panel']) {
    assert.match(css, new RegExp(token.replace('.', '\\.')));
  }

  for (const copy of ['Source-aware', 'No scraped listings', 'Verified before mapped', 'Start browsing the atlas', 'Reset and show all festivals']) {
    assert.match(source, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.match(source, /aria-live="polite"/);
  assert.match(`${css}\n${source}`, /focus-visible/);
});

test('metadata references static social preview and app icon assets', () => {
  const layout = read('src/app/layout.tsx');

  for (const asset of ['public/icon.svg', 'public/apple-icon.svg', 'public/og-preview.svg', 'public/og-preview.png', 'public/manifest.json']) {
    assert.equal(existsSync(join(root, asset)), true, `${asset} should exist`);
  }

  assert.match(layout, /icons:/);
  assert.match(layout, /manifest:/);
  assert.match(layout, /\/manifest\.json/);
  assert.match(layout, /\/icon\.svg/);
  assert.match(layout, /\/apple-icon\.svg/);
  assert.match(layout, /\/og-preview\.png/);
  assert.match(layout, /images:/);
});

test('public launch exposes robots, sitemap, and web manifest metadata routes', () => {
  const robots = read('src/app/robots.ts');
  const sitemap = read('src/app/sitemap.ts');
  const manifest = read('src/app/manifest.ts');

  assert.match(robots, /MetadataRoute\.Robots/);
  assert.match(robots, /sitemap:/);
  assert.match(robots, /https:\/\/retroaltfest\.com\/sitemap\.xml/);

  assert.match(sitemap, /MetadataRoute\.Sitemap/);
  assert.match(sitemap, /featuredFestivals/);
  assert.match(sitemap, /festivalSlug/);
  assert.match(sitemap, /\/festivals/);

  assert.match(manifest, /MetadataRoute\.Manifest/);
  assert.match(manifest, /name: "RetroAltFest"/);
  assert.match(manifest, /start_url: "\/"/);
  assert.match(manifest, /\/icon\.svg/);
});

test('custom analytics logger is disabled for production safety', () => {
  const analyticsRoute = read('src/app/api/analytics/route.ts');
  const layout = read('src/app/layout.tsx');

  assert.doesNotMatch(layout, /<Analytics \/>/);
  assert.doesNotMatch(layout, /components\/analytics\/Analytics/);
  assert.doesNotMatch(analyticsRoute, /\/tmp\/retroaltfest/);
  assert.doesNotMatch(analyticsRoute, /appendFile|writeFile|mkdir/);
  assert.match(analyticsRoute, /204/);
});

test('waitlist uses Buttondown in production with validation and bot protection', () => {
  const component = read('src/components/waitlist/WaitlistSignup.tsx');
  const route = read('src/app/api/waitlist/route.ts');
  const homepage = read('src/app/page.tsx');

  assert.match(component, /use client/);
  assert.match(component, /RetroAltFest festival discovery digest/);
  assert.match(component, /type="email"/);
  assert.match(component, /\/api\/waitlist/);
  assert.match(component, /aria-live="polite"/);
  assert.match(component, /name="website"/);
  assert.match(component, /autoComplete="off"/);
  assert.match(component, /raf-button-primary/);
  assert.doesNotMatch(component, /mailto:hello@retroaltfest\.com/);

  assert.match(route, /BUTTONDOWN_API_KEY/);
  assert.match(route, /https:\/\/api\.buttondown\.com\/v1\/subscribers/);
  assert.match(route, /Authorization/);
  assert.match(route, /Token \$\{buttondownApiKey\}/);
  assert.match(route, /email_address/);
  assert.match(route, /X-Buttondown-Collision-Behavior/);
  assert.match(route, /add/);
  assert.match(route, /honeypot/);
  assert.match(route, /emailRegex/);
  assert.match(route, /process\.env\.VERCEL/);
  assert.doesNotMatch(route, /process\.env\.VERCEL \? "\/tmp\/retroaltfest"/);
  assert.doesNotMatch(route, /\/tmp\/retroaltfest/);
  assert.doesNotMatch(route, /supabase|mongodb|prisma|mailchimp|convertkit/i);

  assert.match(homepage, /<WaitlistSignup \/>/);
});

test('reusable SEO helper centralizes canonical and OG metadata', () => {
  const seo = read('src/lib/seo.ts');
  const layout = read('src/app/layout.tsx');
  const directoryPage = read('src/app/festivals/page.tsx');
  const detailPage = read('src/app/festivals/[slug]/page.tsx');

  assert.match(seo, /siteUrl/);
  assert.match(seo, /defaultOgImage/);
  assert.match(seo, /buildMetadata/);
  assert.match(seo, /canonical/);
  assert.match(seo, /openGraph/);
  assert.match(seo, /twitter/);

  assert.match(layout, /buildMetadata/);
  assert.match(directoryPage, /buildMetadata/);
  assert.match(detailPage, /buildMetadata/);
});

test('festival categories expose the launch taxonomy across data and UI', () => {
  const helpers = read('src/lib/festivals.ts');
  const browser = read('src/components/festivals/FestivalDirectoryBrowser.tsx');
  const card = read('src/components/home/FestivalCard.tsx');
  const data = JSON.parse(read('src/data/seed_festivals_10.json'));
  const requiredCategories = ['darkwave', 'goth', 'industrial', 'synthpop', 'post-punk', 'EDM', 'alternative'];

  for (const category of requiredCategories) {
    assert.match(helpers, new RegExp(category.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
  }

  for (const festival of data.festivals) {
    assert.ok(Array.isArray(festival.categories), `${festival.festival_name} should expose categories`);
    assert.ok(festival.categories.length >= 1, `${festival.festival_name} should have at least one category`);
  }

  assert.match(browser, /categoryFilters/);
  assert.match(browser, /festival\.categories/);
  assert.match(card, /festival\.categories/);
});

test('mobile polish keeps production UI readable on small screens', () => {
  const source = [
    'src/components/home/Hero.tsx',
    'src/components/waitlist/WaitlistSignup.tsx',
    'src/components/festivals/FestivalDirectoryBrowser.tsx',
    'src/app/festivals/[slug]/page.tsx',
  ].map(read).join('\n');

  for (const token of ['text-4xl sm:text-6xl', 'grid-cols-1 sm:grid-cols', 'overflow-x-auto', 'min-w-0']) {
    assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});
