import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();

function read(relativePath) {
  return readFileSync(join(root, relativePath), 'utf8');
}

test('ships the curated festival app data for the homepage vertical slice', () => {
  const dataPath = 'src/data/atlas-festivals.json';
  assert.equal(existsSync(join(root, dataPath)), true, 'seed data should be available in src/data');

  const data = JSON.parse(read(dataPath));
  assert.equal(data.festivals.length, 15);
  assert.equal(data.metadata.record_count, 15);
  assert.equal(new Set(data.festivals.map((record) => record.record_id)).size, 15);
  assert.equal(new Set(data.festivals.map((record) => record.festival_id)).size, 15);
  assert.equal(data.festivals.every((record) => record.official_url && ['high', 'medium'].includes(record.source_confidence)), true);
  assert.equal(data.festivals.every((record) => record.latitude === null && record.longitude === null), true);
  assert.equal(data.festivals.every((record) => record.geocoding_source === null && record.geocoding_query === null), true);
});

test('homepage contains the required RetroAltFest MVP sections and CTAs', () => {
  const homepageSource = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FeaturedFestivals.tsx',
    'src/components/home/SceneChips.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/home/MapPreview.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
  ]
    .filter((sourcePath) => existsSync(join(root, sourcePath)))
    .map(read)
    .join('\n');

  const requiredCopy = [
    'Discover dark alternative festivals worth traveling for.',
    'Browse festivals',
    'Suggest a festival',
    'Map preview',
    'Featured festivals',
    'Browse by scene',
    'Built for fewer dead ends.',
    'Official sources',
    'Clear status labels',
    'Manual curation',
  ];

  for (const copy of requiredCopy) {
    assert.match(homepageSource, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});

test('homepage removes generated template branding and deploy links', () => {
  const homepageSource = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/site/Footer.tsx',
  ]
    .filter((sourcePath) => existsSync(join(root, sourcePath)))
    .map(read)
    .join('\n');

  assert.doesNotMatch(homepageSource, /Next\.js logo|Deploy Now|Templates|Documentation|vercel\.com\/new/);
});

test('global styles define the Nocturnal Atlas design tokens and accessible motion behavior', () => {
  const css = read('src/app/globals.css');
  const requiredTokens = ['--raf-black', '--raf-night', '--raf-violet', '--raf-cyan', '--raf-verified', '--raf-warning'];

  for (const token of requiredTokens) {
    assert.match(css, new RegExp(token));
  }

  assert.match(css, /prefers-reduced-motion/);
});

test('metadata is production-ready for RetroAltFest sharing', () => {
  const layout = read('src/app/layout.tsx');
  assert.match(layout, /RetroAltFest/);
  assert.match(layout, /curated/i);
  assert.match(layout, /dark alternative/i);
  assert.doesNotMatch(layout, /Create Next App|Generated by create next app/);
});

test('homepage MVP uses clean component structure and footer', () => {
  const componentPaths = [
    'src/components/site/Header.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FeaturedFestivals.tsx',
    'src/components/home/SceneChips.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/home/MapPreview.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
    'src/components/site/Footer.tsx',
  ];

  for (const componentPath of componentPaths) {
    assert.equal(existsSync(join(root, componentPath)), true, `${componentPath} should exist`);
  }

  const page = read('src/app/page.tsx');
  assert.match(page, /<Hero/);
  assert.match(page, /<FeaturedFestivals/);
  assert.match(page, /<Footer/);
  assert.doesNotMatch(page, /function FestivalCard/);
});

test('README documents setup, structure, run, and deployment guidance', () => {
  const readme = read('README.md');
  const requiredHeadings = [
    'Project initialization commands',
    'Folder/file structure',
    'Run instructions',
    'Deployment recommendations',
  ];

  for (const heading of requiredHeadings) {
    assert.match(readme, new RegExp(heading, 'i'));
  }
});

test('visual refinement pass deepens atmosphere without heavy dependencies', () => {
  const css = read('src/app/globals.css');
  const source = [
    'src/app/page.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FestivalCard.tsx',
    'src/components/home/MapPreview.tsx',
  ].map(read).join('\n');

  for (const token of ['ambient-haze', 'grain-field', 'atlas-node', 'connection-arc', 'verification-glyph']) {
    assert.match(`${css}\n${source}`, new RegExp(token));
  }

  for (const animation of ['raf-drift', 'raf-pulse', 'raf-grain']) {
    assert.match(css, new RegExp(animation));
  }

  assert.doesNotMatch(`${css}\n${source}`, /framer-motion|lottie|canvas|three/i);
});

test('visual refinement plan separates MVP-safe upgrades from future enhancements', () => {
  const planPath = 'VISUAL_REFINEMENT_PLAN.md';
  assert.equal(existsSync(join(root, planPath)), true, 'visual refinement plan should exist');
  const plan = read(planPath);

  for (const section of ['UI refinement recommendations', 'Implementation plan', 'MVP-safe upgrades', 'Future enhancements', 'Performance considerations']) {
    assert.match(plan, new RegExp(section, 'i'));
  }
});

test('map preview avoids ambiguous truncated country labels', () => {
  const helpers = read('src/lib/festivals.ts');
  const mapPreview = read('src/components/home/MapPreview.tsx');

  assert.match(helpers, /mapPreviewLabel/);
  assert.match(mapPreview, /mapPreviewLabel\(festival\)/);
  assert.doesNotMatch(mapPreview, /country\.split\(" "\)\[0\]/);
});

test('festival data is expandable for atlas detail pages', () => {
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  assert.equal(data.festivals.length, 15);

  for (const festival of data.festivals) {
    assert.match(festival.slug, /^[a-z0-9]+(?:-[a-z0-9]+)*$/);
    assert.equal(typeof festival.atlas_summary, 'string');
    assert.ok(festival.atlas_summary.length > 80);
    assert.equal(typeof festival.why_it_matters, 'string');
    assert.ok(festival.why_it_matters.length > 120);
    assert.ok(Array.isArray(festival.source_links), `${festival.festival_name} should expose labeled source links`);
    assert.ok(festival.source_links.length >= 1);
    assert.ok(festival.source_links.every((link) => link.label && link.url && /^https?:\/\//.test(link.url)));
    assert.ok(Array.isArray(festival.similar_festival_ids), `${festival.festival_name} should list similar festival ids`);
    assert.ok(festival.similar_festival_ids.length >= 2);
  }
});

test('North America 8 integration adds only approved app-data records and keeps excluded records out', () => {
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  const ids = new Set(data.festivals.map((record) => record.festival_id));
  const slugs = new Set(data.festivals.map((record) => record.slug));
  const approved = [
    'cold-waves',
    'absolution-fest',
    'darker-waves',
    'levitation',
    'mutek-montreal',
    'just-like-heaven',
    'the-new-colossus-festival',
    'terminus-festival',
  ];
  const excluded = [
    'sled-island',
    'cruel-world',
    'dark-force-fest',
    'sanctum-festival',
    'dark-castle-fest',
    'verboden-music-festival',
    'mechanismus-festival',
    'mechanismus',
  ];

  for (const id of approved) {
    assert.equal(ids.has(id), true, `${id} should be integrated as app data`);
    assert.equal(slugs.has(id), true, `${id} should have a stable clean slug`);
  }

  for (const id of excluded) {
    assert.equal(ids.has(id), false, `${id} should not be integrated as app data in this batch`);
    assert.equal(slugs.has(id), false, `${id} should not have a public festival detail slug in this batch`);
  }
});

test('North America 8 records preserve source-aware caveats and map safety', () => {
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  const byId = new Map(data.festivals.map((record) => [record.festival_id, record]));

  for (const id of ['cold-waves', 'absolution-fest', 'darker-waves', 'levitation', 'mutek-montreal', 'just-like-heaven', 'the-new-colossus-festival', 'terminus-festival']) {
    const festival = byId.get(id);
    assert.ok(festival, `${id} should exist`);
    assert.equal(festival.latitude, null);
    assert.equal(festival.longitude, null);
    assert.equal(festival.geocoding_source, null);
    assert.equal(festival.geocoding_query, null);
    assert.equal(festival.geocoding_confidence, 'not_geocoded');
    assert.equal(festival.verification_status, 'confirmed_upcoming');
    assert.ok(festival.source_links.length >= 1);
    assert.ok(festival.similar_festival_ids.every((similarId) => byId.has(similarId)), `${id} should only link to integrated records`);
  }

  assert.match(byId.get('levitation').data_quality_notes, /not every show fits RetroAltFest|broad/i);
  assert.match(byId.get('levitation').map_notes, /Parent\/multi-venue|No single map pin/i);
  assert.match(byId.get('mutek-montreal').data_quality_notes, /not specifically goth\/darkwave|Do not frame as goth\/darkwave-specific/i);
  assert.match(byId.get('the-new-colossus-festival').data_quality_notes, /broad|Avoid core goth\/darkwave/i);
  assert.match(byId.get('terminus-festival').data_quality_notes, /do not use unverified full-lineup poster transcription/i);
  assert.match(byId.get('terminus-festival').source_urls.join('\n'), /eventbrite\.ca\/e\/terminus-festival-2026-resonance/);
});

test('festival detail route is static-first and SEO-ready', () => {
  const detailPath = 'src/app/festivals/[slug]/page.tsx';
  assert.equal(existsSync(join(root, detailPath)), true, 'dynamic festival detail route should exist');

  const detailPage = read(detailPath);
  const helpers = read('src/lib/festivals.ts');

  assert.match(detailPage, /generateStaticParams/);
  assert.match(detailPage, /generateMetadata/);
  assert.match(detailPage, /params: Promise<\{ slug: string \}>/);
  assert.match(detailPage, /notFound\(\)/);
  assert.match(detailPage, /Why this festival matters/);
  assert.match(detailPage, /Official sources/);
  assert.match(detailPage, /Verification notes/);
  assert.match(detailPage, /Similar festivals/);
  assert.match(detailPage, /grid-cols-\[|sm:grid-cols|lg:grid-cols/);
  assert.doesNotMatch(detailPage, /use client|fetch\(|prisma|supabase|mongodb|auth/i);

  assert.match(helpers, /festivalSlug/);
  assert.match(helpers, /getFestivalBySlug/);
  assert.match(helpers, /getSimilarFestivals/);
});

test('homepage cards link into the curated festival atlas', () => {
  const card = read('src/components/home/FestivalCard.tsx');
  assert.match(card, /next\/link/);
  assert.match(card, /href=\{`\/festivals\/\$\{festival\.slug\}`\}/);
  assert.match(card, /View atlas entry/);
});

test('festival directory route lists the atlas with lightweight filters and search', () => {
  const directoryPath = 'src/app/festivals/page.tsx';
  const browserPath = 'src/components/festivals/FestivalDirectoryBrowser.tsx';

  assert.equal(existsSync(join(root, directoryPath)), true, 'static /festivals directory page should exist');
  assert.equal(existsSync(join(root, browserPath)), true, 'directory browser component should exist');

  const directoryPage = read(directoryPath);
  const browser = read(browserPath);

  assert.match(directoryPage, /metadata: Metadata/);
  assert.match(directoryPage, /FestivalDirectoryBrowser/);
  assert.match(directoryPage, /publicFestivalDirectoryItems/);
  assert.match(directoryPage, /Curated festival atlas/);
  assert.doesNotMatch(directoryPage, /fetch\(|prisma|supabase|mongodb|auth|cms/i);

  for (const copy of ['Search by festival or location', 'All scenes', 'All regions', 'All statuses', 'No festivals match']) {
    assert.match(browser, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.match(browser, /use client/);
  assert.match(browser, /useMemo/);
  assert.match(browser, /useState/);
  assert.match(browser, /festival\.slug/);
  assert.match(browser, /\/festivals\/\$\{festival\.slug\}/);
  assert.match(browser, /filteredFestivals\.map/);
  assert.match(browser, /grid gap-4|sm:grid-cols|lg:grid-cols/);
  assert.doesNotMatch(browser, /framer-motion|lottie|three|canvas|axios/i);
});

test('public launch polish adds accessible states and clearer trust microcopy', () => {
  const css = read('src/app/globals.css');
  const source = [
    'src/components/site/Header.tsx',
    'src/components/site/Footer.tsx',
    'src/components/home/Hero.tsx',
    'src/components/home/FestivalCard.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/festivals/FestivalDirectoryBrowser.tsx',
    'src/components/home/SubmitFestivalCta.tsx',
  ].map(read).join('\n');

  for (const token of ['.raf-button-primary', '.raf-button-secondary', '.raf-chip', '.raf-panel']) {
    assert.match(css, new RegExp(token.replace('.', '\\.')));
  }

  for (const copy of ['Source-aware', 'No scraped listings', 'Verified before mapped', 'Start browsing the atlas', 'Reset and show all festivals']) {
    assert.match(source, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.match(source, /aria-live="polite"/);
  assert.match(`${css}\n${source}`, /focus-visible/);
});

test('metadata references static social preview and app icon assets', () => {
  const layout = read('src/app/layout.tsx');

  for (const asset of ['public/icon.svg', 'public/apple-icon.svg', 'public/og-preview.svg', 'public/og-preview.png', 'public/manifest.json']) {
    assert.equal(existsSync(join(root, asset)), true, `${asset} should exist`);
  }

  assert.match(layout, /icons:/);
  assert.match(layout, /manifest:/);
  assert.match(layout, /\/manifest\.json/);
  assert.match(layout, /\/icon\.svg/);
  assert.match(layout, /\/apple-icon\.svg/);
  assert.match(layout, /\/og-preview\.png/);
  assert.match(layout, /images:/);
});

test('public launch exposes robots, sitemap, and web manifest metadata routes', () => {
  const robots = read('src/app/robots.ts');
  const sitemap = read('src/app/sitemap.ts');
  const manifest = read('src/app/manifest.ts');

  assert.match(robots, /MetadataRoute\.Robots/);
  assert.match(robots, /sitemap:/);
  assert.match(robots, /https:\/\/retroaltfest\.com\/sitemap\.xml/);

  assert.match(sitemap, /MetadataRoute\.Sitemap/);
  assert.match(sitemap, /featuredFestivals/);
  assert.match(sitemap, /festivalSlug/);
  assert.match(sitemap, /\/festivals/);
  assert.match(sitemap, /\/guides\/north-american-goth-darkwave-festivals/);
  assert.match(sitemap, /\/guides\/industrial-ebm-dark-electronic-festivals-north-america/);
  assert.doesNotMatch(sitemap, /terminus-festival-resonance/);

  assert.match(manifest, /MetadataRoute\.Manifest/);
  assert.match(manifest, /name: "RetroAltFest"/);
  assert.match(manifest, /start_url: "\/"/);
  assert.match(manifest, /\/icon\.svg/);
});

test('legacy Terminus resonance slug redirects to the canonical atlas entry', () => {
  const legacyRedirectPath = 'src/app/festivals/terminus-festival-resonance/route.ts';
  assert.equal(existsSync(join(root, legacyRedirectPath)), true, 'legacy Terminus redirect route should exist');

  const redirectRoute = read(legacyRedirectPath);
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  const slugs = new Set(data.festivals.map((record) => record.slug));

  assert.match(redirectRoute, /NextResponse\.redirect/);
  assert.match(redirectRoute, /\/festivals\/terminus-festival/);
  assert.match(redirectRoute, /301/);
  assert.equal(slugs.has('terminus-festival'), true, 'canonical Terminus slug should remain active');
  assert.equal(slugs.has('terminus-festival-resonance'), false, 'legacy Terminus slug should not become an atlas record');
});

test('custom analytics logger is disabled for production safety', () => {
  const analyticsRoute = read('src/app/api/analytics/route.ts');
  const layout = read('src/app/layout.tsx');

  assert.doesNotMatch(layout, /<Analytics \/>/);
  assert.doesNotMatch(layout, /components\/analytics\/Analytics/);
  assert.doesNotMatch(analyticsRoute, /\/tmp\/retroaltfest/);
  assert.doesNotMatch(analyticsRoute, /appendFile|writeFile|mkdir/);
  assert.match(analyticsRoute, /204/);
});

test('waitlist uses Buttondown in production with validation and bot protection', () => {
  const component = read('src/components/waitlist/WaitlistSignup.tsx');
  const route = read('src/app/api/waitlist/route.ts');
  const homepage = read('src/app/page.tsx');

  assert.match(component, /use client/);
  assert.match(component, /RetroAltFest festival discovery digest/);
  assert.match(component, /type="email"/);
  assert.match(component, /\/api\/waitlist/);
  assert.match(component, /aria-live="polite"/);
  assert.match(component, /name="website"/);
  assert.match(component, /autoComplete="off"/);
  assert.match(component, /raf-button-primary/);
  assert.doesNotMatch(component, /mailto:hello@retroaltfest\.com/);

  assert.match(route, /BUTTONDOWN_API_KEY/);
  assert.match(route, /https:\/\/api\.buttondown\.com\/v1\/subscribers/);
  assert.match(route, /Authorization/);
  assert.match(route, /authorizationHeader/);
  assert.match(route, /email_address/);
  assert.match(route, /X-Buttondown-Collision-Behavior/);
  assert.match(route, /add/);
  assert.match(route, /honeypot/);
  assert.match(route, /emailRegex/);
  assert.match(route, /process\.env\.VERCEL/);
  assert.doesNotMatch(route, /process\.env\.VERCEL \? "\/tmp\/retroaltfest"/);
  assert.doesNotMatch(route, /\/tmp\/retroaltfest/);
  assert.doesNotMatch(route, /supabase|mongodb|prisma|mailchimp|convertkit/i);

  assert.match(homepage, /<WaitlistSignup \/>/);
});

test('reusable SEO helper centralizes canonical and OG metadata', () => {
  const seo = read('src/lib/seo.ts');
  const layout = read('src/app/layout.tsx');
  const directoryPage = read('src/app/festivals/page.tsx');
  const detailPage = read('src/app/festivals/[slug]/page.tsx');

  assert.match(seo, /siteUrl/);
  assert.match(seo, /defaultOgImage/);
  assert.match(seo, /buildMetadata/);
  assert.match(seo, /canonical/);
  assert.match(seo, /openGraph/);
  assert.match(seo, /twitter/);

  assert.match(layout, /buildMetadata/);
  assert.match(directoryPage, /buildMetadata/);
  assert.match(detailPage, /buildMetadata/);
});

test('festival categories expose the launch taxonomy across data and UI', () => {
  const helpers = read('src/lib/festivals.ts');
  const browser = read('src/components/festivals/FestivalDirectoryBrowser.tsx');
  const card = read('src/components/home/FestivalCard.tsx');
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  const requiredCategories = ['darkwave', 'goth', 'industrial', 'synthpop', 'post-punk', 'EDM', 'alternative'];

  for (const category of requiredCategories) {
    assert.match(helpers, new RegExp(category.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'));
  }

  for (const festival of data.festivals) {
    assert.ok(Array.isArray(festival.categories), `${festival.festival_name} should expose categories`);
    assert.ok(festival.categories.length >= 1, `${festival.festival_name} should have at least one category`);
  }

  assert.match(browser, /categoryFilters/);
  assert.match(browser, /festival\.sceneTags/);
  assert.match(card, /festival\.sceneTags/);
});

test('mobile polish keeps production UI readable on small screens', () => {
  const source = [
    'src/components/home/Hero.tsx',
    'src/components/waitlist/WaitlistSignup.tsx',
    'src/components/festivals/FestivalDirectoryBrowser.tsx',
    'src/app/festivals/[slug]/page.tsx',
  ].map(read).join('\n');

  for (const token of ['text-4xl sm:text-6xl', 'grid-cols-1 sm:grid-cols', 'overflow-x-auto', 'min-w-0']) {
    assert.match(source, new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }
});

test('first dark festival signals data matches the locked MVP content packet', () => {
  const dataPath = 'src/data/first_dark_festival_signals.json';
  assert.equal(existsSync(join(root, dataPath)), true, 'locked six-card signal data should exist');

  const data = JSON.parse(read(dataPath));
  const expectedOrder = [
    'darker-waves',
    'dark-force-fest',
    'cold-waves',
    'verboden-music-festival',
    'absolution-fest',
    'cruel-world',
  ];

  assert.equal(data.section.eyebrow, 'North America first');
  assert.equal(data.section.title, 'First Dark Festival Signals');
  assert.equal(
    data.section.clarification_note,
    'Signal cards mix active atlas entries with tracked festival leads. Some items are fully listed in the atlas, while others are reference or future-edition signals we’re monitoring until official dates, locations, or source confidence are stronger.',
  );
  assert.equal(data.signals.length, 6);
  assert.deepEqual(data.signals.map((signal) => signal.id), expectedOrder);
  assert.equal(new Set(data.signals.map((signal) => signal.id)).size, 6);

  for (const signal of data.signals) {
    assert.equal(signal.priority, 'homepage_core');
    assert.ok(signal.name);
    assert.ok(signal.region_label);
    assert.ok(['USA', 'North America'].includes(signal.country_scope));
    assert.ok(Array.isArray(signal.scene_tags));
    assert.ok(signal.scene_tags.length >= 2 && signal.scene_tags.length <= 3);
    assert.ok(['Confirmed upcoming', 'Date pending', 'Reference only', 'Needs future-edition refresh'].includes(signal.status_label));
    assert.ok(['confirmed_upcoming', 'date_pending', 'reference_only', 'needs_future_refresh'].includes(signal.status_key));
    assert.ok(signal.cultural_hook.length > 40 && signal.cultural_hook.length <= 120);
    assert.match(signal.source_cue, /^Official source tracked/);
    assert.match(signal.official_url, /^https?:\/\//);
    assert.ok(signal.art_direction);
    assert.ok(signal.editorial_descriptor);
    assert.ok(signal.why_this_matters);
    assert.ok(signal.pathway_concept);
    assert.ok(signal.seasonal_relevance);
    assert.ok(signal.scene_relationships);
    assert.ok(signal.source_confidence_notes);
  }
});

test('first dark festival signals content stays restrained and source-aware', () => {
  const data = JSON.parse(read('src/data/first_dark_festival_signals.json'));
  const publicCopy = [
    data.section.eyebrow,
    data.section.title,
    data.section.subtitle,
    data.section.trust_note,
    data.section.clarification_note,
    data.section.closing_microcopy,
    ...data.signals.flatMap((signal) => [
      signal.name,
      signal.region_label,
      signal.status_label,
      signal.cultural_hook,
      signal.source_cue,
      signal.pathway_concept,
    ]),
  ].join('\n');

  assert.doesNotMatch(publicCopy, /complete guide|best festivals|near you|book your trip|buy tickets|all festivals|ultimate directory|trending now|must-see|top festivals|hottest events|do not miss/i);
  assert.doesNotMatch(publicCopy, /needs_review|watchlist/i);
  assert.match(publicCopy, /source-aware/i);
  assert.match(publicCopy, /North America/i);
});

test('first dark festival signals component is restrained, semantic, and data-backed', () => {
  const componentPath = 'src/components/home/FirstDarkFestivalSignals.tsx';
  assert.equal(existsSync(join(root, componentPath)), true, 'homepage signal module component should exist');

  const component = read(componentPath);
  const data = JSON.parse(read('src/data/first_dark_festival_signals.json'));

  assert.match(component, /first_dark_festival_signals\.json/);
  assert.match(component, /<section/);
  assert.match(component, /aria-labelledby="first-dark-festival-signals-heading"/);
  assert.match(component, /id="first-dark-festival-signals-heading"/);
  assert.match(component, /grid-cols-1/);
  assert.match(component, /md:grid-cols-2/);
  assert.match(component, /xl:grid-cols-3/);
  assert.match(component, /editorial-card-glow/);
  assert.match(component, /raf-chip/);
  assert.match(component, /target="_blank"/);
  assert.match(component, /rel="noopener noreferrer"/);
  assert.doesNotMatch(component, /use client|useState|useMemo|carousel|filter|search|modal|canvas|framer-motion|lottie|three/i);

  assert.equal(data.signals.length, 6);
});

test('first dark festival signals module is placed directly after the hero', () => {
  const page = read('src/app/page.tsx');
  assert.match(page, /components\/home\/FirstDarkFestivalSignals/);

  const heroIndex = page.indexOf('<Hero />');
  const signalsIndex = page.indexOf('<FirstDarkFestivalSignals />');
  const trustIndex = page.indexOf('<TrustSection />');
  const mapIndex = page.indexOf('<MapPreview />');

  assert.ok(heroIndex > -1, 'Hero should still render');
  assert.ok(signalsIndex > heroIndex, 'Signals module should render after Hero');
  assert.ok(trustIndex > signalsIndex, 'Existing trust section should remain after Signals module');
  assert.ok(mapIndex > signalsIndex, 'Existing map preview should remain after Signals module');
});

test('guide page for North American goth and darkwave festivals is static, bounded, and source-safe', () => {
  const guidePath = 'src/app/guides/north-american-goth-darkwave-festivals/page.tsx';
  assert.equal(existsSync(join(root, guidePath)), true, 'guide route should exist');

  const guide = read(guidePath);
  const requiredCopy = [
    'North American Goth &amp; Darkwave Festivals: A Curated Guide',
    'source-aware North American guide',
    'official or organizer-controlled sources',
    'See how RetroAltFest handles verification',
    'Source-supported active atlas records',
    'Active atlas record with 2026 source support',
    'A Murder of Crows XI NYC Goth & Post-punk Festival',
    'Reference signal — checked 2026 dates have passed',
    'Related gateway — future date not confirmed',
    'Recently active corridor signal — recheck future edition',
    'How RetroAltFest labels this guide',
    'href="/verification"',
    'href="/festivals"',
    'href="/guides"',
    'atlasPath: "/festivals/absolution-fest"',
    'atlasPath: "/festivals/a-murder-of-crows-xi-nyc-goth-post-punk-festival"',
    'atlasPath: "/festivals/cold-waves"',
    'atlasPath: "/festivals/terminus-festival"',
  ];

  for (const copy of requiredCopy) {
    assert.match(guide, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  for (const includedRecord of ['Absolution Fest', 'Cold Waves', 'Terminus Festival', 'Verboden Music Festival', 'Dark Force Fest', 'Cruel World']) {
    assert.match(guide, new RegExp(includedRecord));
  }

  for (const blockedScope of ['Darker Waves', 'Mechanismus', 'Substance', 'Riot Fest', 'Levitation']) {
    assert.doesNotMatch(guide, new RegExp(blockedScope));
  }

  assert.doesNotMatch(guide, /atlasPath: "\/festivals\/(dark-force-fest|cruel-world|verboden-music-festival)"/);
  assert.doesNotMatch(guide, /Currently confirmed|active upcoming cycle|tickets available/i);
  assert.doesNotMatch(guide, /latitude|longitude|geocodingSource|geocoding_source|coordinates|map pins|exact map pin|map placement/i);
  assert.doesNotMatch(guide, /fetch\(|prisma|supabase|mongodb|auth|cms|scrap/i);

  const featuredFestivals = read('src/components/home/FeaturedFestivals.tsx');
  assert.match(featuredFestivals, /Explore RetroAltFest Guides/);
  assert.match(featuredFestivals, /href="\/guides"/);
});

test('guide page for industrial EBM and dark electronic festivals is static, bounded, and source-safe', () => {
  const guidePath = 'src/app/guides/industrial-ebm-dark-electronic-festivals-north-america/page.tsx';
  assert.equal(existsSync(join(root, guidePath)), true, 'industrial guide route should exist');

  const guide = read(guidePath);
  const requiredCopy = [
    'Industrial, EBM &amp; Dark Electronic Festivals in North America',
    'source-aware North American guide',
    'official or organizer-controlled sources',
    'See how RetroAltFest verifies festival records',
    'Active industrial / dark electronic atlas records',
    'Core active atlas records with current source support',
    'Cold Waves',
    'Terminus Festival',
    'Mechanismus',
    'Verboden Music Festival',
    'Dark Force Fest',
    'Absolution Fest',
    'Core industrial / dark electronic atlas record',
    'Core industrial / EBM atlas record',
    'Related dark-scene overlap',
    'Tracked Seattle industrial scene signal',
    'Recently active corridor signal',
    'Reference/background signal',
    'Held from public card treatment',
    'Triton Festival stays held for now',
    'href="/verification"',
    'href="/festivals"',
    '/guides/north-american-goth-darkwave-festivals',
    'atlasPath: "/festivals/cold-waves"',
    'atlasPath: "/festivals/terminus-festival"',
    'atlasPath: "/festivals/absolution-fest"',
  ];

  for (const copy of requiredCopy) {
    assert.match(guide, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.doesNotMatch(guide, /atlasPath: "\/festivals\/(mechanismus|verboden-music-festival|dark-force-fest|triton-festival)"/);
  assert.doesNotMatch(guide, /\/festivals\/(mechanismus|verboden-music-festival|dark-force-fest|triton-festival)/);
  assert.doesNotMatch(guide, /currently confirmed examples|confirmed festivals|upcoming|tickets available/i);
  assert.doesNotMatch(guide, /latitude|longitude|geocodingSource|geocoding_source|coordinates|geocoding|map-ready|map placement|map pin|future map|later city-level map review/i);
  assert.doesNotMatch(guide, /fetch\(|prisma|supabase|mongodb|auth|cms|scrap/i);

  const featuredFestivals = read('src/components/home/FeaturedFestivals.tsx');
  assert.match(featuredFestivals, /Explore RetroAltFest Guides/);
  assert.match(featuredFestivals, /href="\/guides"/);
});

test('guide page for new wave post-punk and retro alternative festivals is static, bounded, and source-safe', () => {
  const guidePath = 'src/app/guides/new-wave-post-punk-retro-alternative-festivals-north-america/page.tsx';
  assert.equal(existsSync(join(root, guidePath)), true, 'new wave/post-punk guide route should exist');

  const guide = read(guidePath);
  const requiredCopy = [
    'New Wave, Post-Punk &amp; Retro Alternative Festivals in North America',
    'Start here for North American new wave, post-punk, retro alternative, synth-era, and related indie-nostalgia festival discovery.',
    'Who this guide is for',
    'How to use this guide',
    'Where to start',
    'Scene and vibe notes',
    'Source-supported active atlas record',
    'Darker Waves',
    '/festivals/darker-waves',
    'Related active atlas records',
    'Just Like Heaven',
    '/festivals/just-like-heaven',
    'The New Colossus Festival',
    '/festivals/the-new-colossus-festival',
    'Reference points, not active atlas links here',
    'Cruel World',
    'Riot Fest',
    'Why some names are not linked',
    'Short FAQ',
    'Related RetroAltFest paths',
    'See how RetroAltFest verifies festival records',
    '/verification',
    '/guides/north-american-goth-darkwave-festivals',
    '/guides/industrial-ebm-dark-electronic-festivals-north-america',
    '/guides/west-coast-pacific-northwest-dark-alternative-festivals',
    'href="/festivals"',
  ];

  for (const copy of requiredCopy) {
    assert.match(guide, new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  }

  assert.doesNotMatch(guide, /festivalName: "Kilby Block Party"/);
  assert.doesNotMatch(guide, /festivalName: "Best Friends Forever Fest"/);
  assert.doesNotMatch(guide, /festivalName: "When We Were Young"/);
  assert.doesNotMatch(guide, /\/festivals\/cruel-world/);
  assert.doesNotMatch(guide, /\/festivals\/riot-fest/);
  assert.doesNotMatch(guide, /Currently confirmed/);
  assert.doesNotMatch(guide, /upcoming|tickets available|passes on sale|featuring|lineup includes|full lineup/i);
  assert.doesNotMatch(guide, /complete list|full directory|confirmed-current claims|best festivals/i);
  assert.doesNotMatch(guide, /latitude|longitude|geocodingSource|geocoding_source|coordinates|geocoding|map-ready|map placement|map pin|future map|later city-level map review/i);
  assert.doesNotMatch(guide, /date_pending|source_status|Phase 0|map-readiness|watchlist|core_anchor|confirmed_upcoming|mapDisplayCategory|public V1|source sufficiency|record type|overlap risk|adjacent_reference/i);
  assert.doesNotMatch(guide, /fetch\(|prisma|supabase|mongodb|auth|cms|scrap/i);

  const featuredFestivals = read('src/components/home/FeaturedFestivals.tsx');
  const sitemap = read('src/app/sitemap.ts');
  assert.match(featuredFestivals, /Explore RetroAltFest Guides/);
  assert.match(featuredFestivals, /href="\/guides"/);
  assert.match(sitemap, /\/guides\/new-wave-post-punk-retro-alternative-festivals-north-america/);
});

test('guide page for West Coast and Pacific Northwest dark alternative festivals is static, bounded, and source-safe', () => {
  const guidePath = 'src/app/guides/west-coast-pacific-northwest-dark-alternative-festivals/page.tsx';
  assert.equal(existsSync(join(root, guidePath)), true, 'West Coast / PNW guide route should exist');

  const guide = read(guidePath);
  const requiredCopy = [
    'West Coast &amp; Pacific Northwest Dark Alternative Festivals',
    'A curated regional route through active atlas records, recently active festival signals, and carefully caveated dark alternative source trails from Southern California to Portland, Seattle, and Vancouver.',
    'Southern California anchors',
    'Pacific Northwest corridor',
    'Darker Waves',
    'Cruel World',
    'Just Like Heaven',
    'Verboden Music Festival — Vancouver',
    'Verboden Music Festival — Seattle',
    'Verboden Music Festival — Portland',
    'Mechanismus',
    'Related festival to know',
    'active RetroAltFest atlas record',
    'recently active',
    'The checked official pages did not confirm a future edition',
    'Do not say tickets are available',
    'Exact future festival dates, festival venue, tickets, and lineup are not confirmed',
    'not as a darkwave or industrial anchor',
    'Spokane has an official-linked Verboden Showcase source trail',
    'Useful leads, but not public guide cards yet.',
    'Substance — Los Angeles',
    'Substance — San Francisco',
    'The Vth Gathering / San Francisco World Goth Day Festival — Alameda',
    'Out From The Shadows — Portland',
    'West Coast Women’s Darkwave Festival — Oakland',
    'Cloak & Dagger Festival — Los Angeles',
    '/guides/north-american-goth-darkwave-festivals',
    '/guides/industrial-ebm-dark-electronic-festivals-north-america',
    '/guides/new-wave-post-punk-retro-alternative-festivals-north-america',
    'href="/verification"',
    'href="/festivals"',
    'href={record.atlasPath}',
    'atlasPath: "/festivals/darker-waves"',
    'atlasPath: "/festivals/just-like-heaven"',
  ];

  for (const copy of requiredCopy) {
    assert.match(guide, new RegExp(copy.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')));
  }

  const publicCardNames = [...guide.matchAll(/festivalName: "([^"]+)"/g)].map((match) => match[1]);
  assert.deepEqual(publicCardNames, [
    'Darker Waves',
    'Cruel World',
    'Just Like Heaven',
    'Verboden Music Festival — Vancouver',
    'Verboden Music Festival — Seattle',
    'Verboden Music Festival — Portland',
    'Mechanismus',
  ]);

  for (const blockedCard of ['Spokane', 'Substance', 'The Vth Gathering', 'Out From The Shadows', 'West Coast Women’s Darkwave Festival', 'Cloak & Dagger']) {
    assert.doesNotMatch(guide, new RegExp(`festivalName: "[^"]*${blockedCard}`));
  }

  assert.doesNotMatch(guide, /Day 3 public content packet|Purpose:|Source safety checklist|Completion status/);
  assert.doesNotMatch(guide, /source_status|map-readiness|public V1|city_level_candidate|parent_only|date_pending|core_anchor|adjacent_reference|source_sufficiency|Phase 0|map_phase0_category/i);
  assert.doesNotMatch(guide, /latitude|longitude|geocodingSource|geocoding_source|coordinates|map pins|exact map pin/i);
  assert.doesNotMatch(guide, /fetch\(|prisma|supabase|mongodb|auth|cms|scrap/i);

  const featuredFestivals = read('src/components/home/FeaturedFestivals.tsx');
  const sitemap = read('src/app/sitemap.ts');
  const guidesPage = read('src/app/guides/page.tsx');
  assert.match(featuredFestivals, /West Coast \/ PNW/);
  assert.match(featuredFestivals, /regional West Coast \/ PNW discovery/);
  assert.match(guidesPage, /\/guides\/west-coast-pacific-northwest-dark-alternative-festivals/);
  assert.match(guidesPage, /Regional discovery across Southern California and the Pacific Northwest, with active atlas anchors, recently active corridor signals, and source-aware caveats\./);
  assert.match(sitemap, /\/guides\/west-coast-pacific-northwest-dark-alternative-festivals/);
});

test('public verification page explains source checks without exposing internal workflow labels', () => {
  const verificationPath = 'src/app/verification/page.tsx';
  assert.equal(existsSync(join(root, verificationPath)), true, 'static /verification page should exist');

  const verificationPage = read(verificationPath);
  const homepageTrust = read('src/components/home/TrustSection.tsx');
  const festivalsPage = read('src/app/festivals/page.tsx');
  const guidesPage = read('src/app/guides/page.tsx');
  const festivalDetailPage = read('src/app/festivals/[slug]/page.tsx');
  const sitemap = read('src/app/sitemap.ts');

  for (const copy of [
    'How RetroAltFest Verifies Festivals | RetroAltFest',
    'How RetroAltFest verifies festivals',
    'Verified before mapped',
    'Confirmed upcoming',
    'Dates not announced yet',
    'Source check in progress',
    'Not ready for map placement yet',
    'A map pin implies confidence',
  ]) {
    assert.match(verificationPage, new RegExp(copy.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')));
  }

  assert.match(verificationPage, /metadata: Metadata/);
  assert.match(verificationPage, /buildMetadata/);
  assert.match(verificationPage, /path: pagePath/);
  assert.match(verificationPage, /href="\/festivals"/);
  assert.match(verificationPage, /href="\/guides"/);
  assert.doesNotMatch(verificationPage, /fetch\(|prisma|supabase|mongodb|auth|cms|scrap|api\//i);
  assert.doesNotMatch(verificationPage, /date_pending|Phase 0|map-readiness|core_anchor|source_status|map_phase0_category|geocoding_source|latitude|longitude|coordinates/i);

  for (const source of [homepageTrust, festivalsPage, guidesPage, festivalDetailPage, sitemap]) {
    assert.match(source, /\/verification/);
  }
});

test('guides index is static, compact, and lists exactly the four live curated scene guides', () => {
  const guidesPath = 'src/app/guides/page.tsx';
  assert.equal(existsSync(join(root, guidesPath)), true, 'static /guides page should exist');

  const guidesPage = read(guidesPath);
  const homepage = read('src/components/home/FeaturedFestivals.tsx');
  const sitemap = read('src/app/sitemap.ts');

  const guideHrefs = [
    '/guides/west-coast-pacific-northwest-dark-alternative-festivals',
    '/guides/north-american-goth-darkwave-festivals',
    '/guides/industrial-ebm-dark-electronic-festivals-north-america',
    '/guides/new-wave-post-punk-retro-alternative-festivals-north-america',
  ];

  assert.match(guidesPage, /RetroAltFest Guides/);
  assert.match(guidesPage, /Start here for curated paths into goth, darkwave, industrial, EBM, post-punk, new wave, and retro alternative festivals\./);
  assert.match(guidesPage, /RetroAltFest Guides \| Goth, Darkwave, Industrial & Retro Alternative Festivals/);
  assert.match(guidesPage, /we check official or reliable sources/);

  for (const href of guideHrefs) {
    assert.match(guidesPage, new RegExp(href.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
    assert.equal(existsSync(join(root, `src/app${href}/page.tsx`)), true, `${href} should still exist`);
  }

  const hrefMatches = [...guidesPage.matchAll(/href: "(\/guides\/[^"]+)"/g)].map((match) => match[1]);
  assert.deepEqual(hrefMatches, guideHrefs);

  assert.match(homepage, /Explore RetroAltFest Guides/);
  assert.match(homepage, /href="\/guides"/);
  assert.doesNotMatch(homepage, /href="\/guides\/new-wave-post-punk-retro-alternative-festivals-north-america"/);
  assert.doesNotMatch(homepage, /href="\/guides\/industrial-ebm-dark-electronic-festivals-north-america"/);
  assert.doesNotMatch(homepage, /href="\/guides\/north-american-goth-darkwave-festivals"/);

  assert.match(sitemap, /`\$\{SITE_URL\}\/guides`/);
  assert.doesNotMatch(guidesPage, /future guide|coming soon|placeholder|search|filter|useState|useMemo|fetch\(|prisma|supabase|mongodb|auth|cms|database|geocoding|latitude|longitude|coordinates|map pins/i);
});

test('internal discovery links connect existing routes without fake festival detail pages', () => {
  const data = JSON.parse(read('src/data/atlas-festivals.json'));
  const atlasSlugs = new Set(data.festivals.map((record) => record.slug));
  assert.equal(data.festivals.length, 15);

  const sourcePaths = [
    'src/app/page.tsx',
    'src/app/festivals/page.tsx',
    'src/app/festivals/[slug]/page.tsx',
    'src/app/guides/page.tsx',
    'src/app/guides/north-american-goth-darkwave-festivals/page.tsx',
    'src/app/guides/industrial-ebm-dark-electronic-festivals-north-america/page.tsx',
    'src/app/guides/new-wave-post-punk-retro-alternative-festivals-north-america/page.tsx',
    'src/app/guides/west-coast-pacific-northwest-dark-alternative-festivals/page.tsx',
    'src/app/verification/page.tsx',
    'src/components/site/Header.tsx',
    'src/components/site/Footer.tsx',
    'src/components/site/DiscoveryLinks.tsx',
  ];

  const source = sourcePaths.map(read).join('\n');
  for (const route of ['/festivals', '/guides', '/verification']) {
    assert.match(source, new RegExp(route.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')));
  }

  for (const guide of [
    '/guides/west-coast-pacific-northwest-dark-alternative-festivals',
    '/guides/north-american-goth-darkwave-festivals',
    '/guides/industrial-ebm-dark-electronic-festivals-north-america',
    '/guides/new-wave-post-punk-retro-alternative-festivals-north-america',
  ]) {
    assert.match(source, new RegExp(guide.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&')));
  }

  const festivalLinks = [...source.matchAll(/\/festivals\/([a-z0-9-]+)/g)].map((match) => match[1]);
  for (const slug of festivalLinks) {
    assert.equal(atlasSlugs.has(slug), true, `/festivals/${slug} should be an active atlas route`);
  }

  for (const blockedSlug of ['cruel-world', 'riot-fest', 'dark-force-fest', 'triton-festival', 'verboden-music-festival', 'mechanismus', 'mechanismus-festival']) {
    assert.doesNotMatch(source, new RegExp(`/festivals/${blockedSlug}`));
  }
});

test('discovery flow uses route-safe global navigation instead of local-only footer anchors', () => {
  const header = read('src/components/site/Header.tsx');
  const footer = read('src/components/site/Footer.tsx');
  const homepage = read('src/app/page.tsx');
  const detailPage = read('src/app/festivals/[slug]/page.tsx');

  for (const source of [header, footer]) {
    assert.match(source, /href="\/festivals"/);
    assert.match(source, /href="\/guides"/);
    assert.match(source, /href="\/verification"/);
  }

  assert.doesNotMatch(footer, /href="#(festivals|map|trust|submit)"/);
  assert.match(homepage, /Where should I start\?/);
  assert.match(homepage, /Choose your first RetroAltFest path/);
  assert.match(detailPage, /Continue exploring RetroAltFest/);
});

test('public festival DTO helper defines only approved browser-facing shapes', () => {
  const helperPath = 'src/lib/public-festivals.ts';
  assert.equal(existsSync(join(root, helperPath)), true, 'public DTO helper should exist');

  const helper = read(helperPath);
  for (const exportName of [
    'PublicFestivalDirectoryItem',
    'PublicFeaturedFestival',
    'PublicFestivalDetail',
    'toPublicFestivalDirectoryItem',
    'toPublicFeaturedFestival',
    'toPublicFestivalDetail',
  ]) {
    assert.match(helper, new RegExp(`export (type |function |const )${exportName}`));
  }

  for (const approvedField of [
    'id',
    'slug',
    'name',
    'locationLabel',
    'dateLabel',
    'sceneTags',
    'statusLabel',
    'searchText',
    'summary',
    'sourceConfidenceLabel',
    'coordinateLabel',
    'officialSiteUrl',
    'sourceLinks',
    'similar',
  ]) {
    assert.match(helper, new RegExp(approvedField));
  }
});

test('client-facing festival components use public DTOs instead of raw festival records', () => {
  const directoryPage = read('src/app/festivals/page.tsx');
  const browser = read('src/components/festivals/FestivalDirectoryBrowser.tsx');
  const featured = read('src/components/home/FeaturedFestivals.tsx');
  const card = read('src/components/home/FestivalCard.tsx');

  assert.match(directoryPage, /publicFestivalDirectoryItems/);
  assert.doesNotMatch(directoryPage, /festivalDirectoryRecords/);
  assert.match(browser, /PublicFestivalDirectoryItem/);
  assert.doesNotMatch(browser, /FestivalDirectoryRecord|verification_status|festival_name|record_id|venue_name/);
  assert.match(featured, /publicFeaturedFestivals/);
  assert.doesNotMatch(featured, /featuredFestivals\.map/);
  assert.match(card, /PublicFeaturedFestival/);
  assert.doesNotMatch(card, /import \{ Festival|official_url|verification_status|festival_name|record_id|date_text/);
});

test('festival detail route renders only public detail DTO fields', () => {
  const detailPage = read('src/app/festivals/[slug]/page.tsx');

  assert.match(detailPage, /getPublicFestivalDetailBySlug/);
  assert.match(detailPage, /publicFestivalSlugs/);
  assert.match(detailPage, /festival\.sourceLinks/);
  assert.match(detailPage, /festival\.sourceConfidenceLabel/);
  assert.match(detailPage, /festival\.coordinateLabel/);
  assert.doesNotMatch(detailPage, /geocoding_confidence|geocoding_source|geocoding_query|map_display_category|map_phase0_category|source_status|source_confidence|data_quality_notes|map_notes|official_url|verification_status|festival_name|date_text|venue_name|similar_festival_ids/);
});

test('public route and component sources do not expose blocked internal source-safety terms', () => {
  const publicSourceFiles = [
    'src/app/page.tsx',
    'src/app/festivals/page.tsx',
    'src/app/festivals/[slug]/page.tsx',
    'src/app/guides/page.tsx',
    'src/app/guides/north-american-goth-darkwave-festivals/page.tsx',
    'src/app/guides/industrial-ebm-dark-electronic-festivals-north-america/page.tsx',
    'src/app/guides/new-wave-post-punk-retro-alternative-festivals-north-america/page.tsx',
    'src/app/guides/west-coast-pacific-northwest-dark-alternative-festivals/page.tsx',
    'src/app/verification/page.tsx',
    'src/components/festivals/FestivalDirectoryBrowser.tsx',
    'src/components/home/FestivalCard.tsx',
    'src/components/home/FeaturedFestivals.tsx',
    'src/components/home/MapPreview.tsx',
    'src/components/home/TrustSection.tsx',
    'src/components/home/FirstDarkFestivalSignals.tsx',
  ];

  const blockedPatterns = [
    /geocoding_source/i,
    /geocoding_query/i,
    /geocoding_confidence/i,
    /map_phase0_category/i,
    /source_status/i,
    /source_sufficiency/i,
    /date_pending/i,
    /needs_review/i,
    /core_anchor/i,
    /watchlist/i,
    /Phase 0/i,
    /map-readiness/i,
    /latitude/i,
    /longitude/i,
  ];

  for (const filePath of publicSourceFiles) {
    const source = read(filePath);
    for (const pattern of blockedPatterns) {
      assert.doesNotMatch(source, pattern, `${filePath} should not expose ${pattern}`);
    }
  }
});
